/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function loadingFilesInfo(callback?: (stage: string, processed: number, total: number, label: string) => void): Promise<string>
export function sum(a: number, b: number): number
export interface Pet {
  name: string
  kind: number
}
export function printPet(pet: Pet): void
export function createCat(): Pet
export class NapiGrfResultBuffer {
  matches: string
}
